name: RDP Creator
on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node: ['16']
        include:
        - os: windows-latest
          commandPrefix: ''
    runs-on: ${{ matrix.os }}
    steps:
    - name: RDP - Payload 1 - Importing File
      run: |
        cd C:\
        C:
        C:\Windows\System32\cmd.exe /c md Resource
        cd C:\Resource
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/host3.ps1 -OutFile host.ps1
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/loop1.bat -OutFile loop.bat
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/ngrok.exe -OutFile ngrok.exe
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/req.ps1 -OutFile req.ps1
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/start.bat -OutFile start.bat
        C:\Windows\System32\cmd.exe /c dir
    - name: RDP - Payload 2 - Disable User Password Requirements
      run: |
        cd C:\Resource
        C:
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe .\req.ps1

    - name: RDP - Payload 3 - Host (ngrok)
      run: |
        cd C:\Resource
        C:
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe .\host.ps1

    - name: RDP - Payload 4 - Settings User And More
      run: |
        cd C:\Resource
        C:
        C:\Windows\System32\cmd.exe /c start.bat

    - name: RDP - Payload 5 - Make It Keep Online!
      run: |
        cd C:\Resource
        C:
        C:\Windows\System32\cmd.exe /c loop.bat
