name: Test
on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node: ['16']
        include:
        - os: windows-latest
          commandPrefix: ''
    runs-on: ${{ matrix.os }}
    steps:
    - name: Payload 1 (test cd)
      run: |
        cd C:\
        C:
        C:\Windows\System32\cmd.exe /c dir

    - name: Payload 2 (test create folder)
      run: |
        C:\Windows\System32\cmd.exe /c md C:\Resource
        cd C:\Resource
        C:\Windows\System32\cmd.exe /c dir

    - name: Payload 2 (test importing online file)
      run: |
        cd C:\Resource
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/host.ps1 -OutFile host.ps1
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/loop.bat -OutFile loop.bat
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/ngrok.exe -OutFile ngrok.exe
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/req.ps1 -OutFile req.ps1
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Invoke-WebRequest https://raw.githubusercontent.com/FleterA2/rdp/main/resources/start.bat -OutFile start.bat